# Generated by Django 5.2.11 on 2026-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('desarrollador', 'Desarrollador'), ('investigador', 'Investigador'), ('anotador', 'Anotador'), ('consultor', 'Consultor')], db_index=True, default='consultor', max_length=20),
        ),
    ]
