# Generated by Django 5.2.11 on 2026-05-14 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lengua',
                'verbose_name_plural': 'Lenguas',
                'db_table': 'lenguas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TerminoEs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Término en Español',
                'verbose_name_plural': 'Términos en Español',
                'db_table': 'terminos_es',
                'ordering': ['termino'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('model_name', models.CharField(default='intfloat/multilingual-e5-base', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('ready', 'Listo'), ('active', 'Activo'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('num_terminos', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('embeddings_path', models.CharField(blank=True, max_length=500)),
                ('faiss_path', models.CharField(blank=True, max_length=500)),
                ('metadata_path', models.CharField(blank=True, max_length=500)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lengua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_versions', to='terminos.lengua')),
            ],
            options={
                'verbose_name': 'Versión de Embedding',
                'verbose_name_plural': 'Versiones de Embeddings',
                'db_table': 'embedding_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminoLeng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(db_index=True, max_length=255)),
                ('definicion', models.TextField(blank=True)),
                ('pos', models.CharField(blank=True, max_length=50)),
                ('sinonimos', models.JSONField(blank=True, default=list)),
                ('ejemplos', models.JSONField(blank=True, default=list)),
                ('tipo_morfema', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lengua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos', to='terminos.lengua')),
                ('termino_es', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones', to='terminos.terminoes')),
            ],
            options={
                'verbose_name': 'Término en Lengua Indígena',
                'verbose_name_plural': 'Términos en Lengua Indígena',
                'db_table': 'terminos_leng',
                'ordering': ['termino'],
                'unique_together': {('termino', 'lengua')},
            },
        ),
    ]
